# Generated by Django 5.2.5 on 2025-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
