# Generated by Django 5.2.5 on 2025-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_tags_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
