# Generated by Django 5.2.5 on 2025-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='draft',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
